### ISSUE TITLE
Fix layout for index page

### ISSUE THREAD

**Issue by chanhee-park** [Useful-Dogus/usefuldogus.com#7]
# Bugs to fix
- `height` for header and footer is too large (750px).
- No need to use`min-height` for main, because it uses flex layout.

**Comment by dakyungoh** [comment]
이거 왜 close 안하셨나요? 혹시 아직 할 작업이 남아있나요?

**Comment by chanhee-park** [comment]
엇... 깜빡했네요~ 지금 닫을게요. 감사합니다!
